spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
      url: "jdbc:postgresql://localhost:5432/ems_db"
      username: joseph
      password: password